name: NYUARLibrary CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Running docker-compose build
      run: docker-compose build

    - name: Running docker-compose up
      run: docker-compose up
